name: Lint

on: pull_request

jobs:
  lint:
    name: Ensure GitHub Actions are pinned to SHA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2.3.4
      - name: Ensure GitHub Actions are pinned to SHA
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43 # pin@v1.0.4
